[project]
name = "snakemake-interface-logger-plugins"
version = "0.1.0"
description = "Add your description here"
authors = [{name = "Cade Mirchandani"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "snakemake-interface-common>=1.17.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
